language: python
python:
  - "2.7"
  # - "3.3"
env:
  - SUBLIME_TEXT_VERSION="2" EXPECTED_PATH="/usr/bin/subl"
  - SUBLIME_TEXT_VERSION="3" EXPECTED_PATH="/usr/bin/subl"
  - SUBLIME_TEXT_VERSION="3" SUBLIME_TEXT_RENAME="sublime_text" EXPECTED_PATH="/usr/bin/sublime_text"
  - SUBLIME_TEXT_VERSION="3" SUBLIME_TEXT_RENAME="sublime_texttt" SUBLIME_TEXT_PATH="/usr/bin/sublime_texttt" EXPECTED_PATH="/usr/bin/sublime_texttt"
  - EXPECT_ERROR="1"

install:
  # Install Sublime Text
  - ./test/install.sh

  # Install `sublime_info`
  - python setup.py develop

  # Install dev requirements
  - pip install -r requirements-dev.txt

script:
  # Run our tests
  - ./test.sh

notifications:
  email: false
