language: python
python:
  - "2.7"
  # - "3.3"
env:
  - SUBLIME_TEXT_VERSION="2"
  - SUBLIME_TEXT_VERSION="3"
  - SUBLIME_TEXT_VERSION="3" SUBLIME_TEXT_RENAME="sublime_text"
  - SUBLIME_TEXT_VERSION="3" SUBLIME_TEXT_RENAME="sublime_texttt" SUBLIME_TEXT_PATH="/usr/bin/sublime_texttt"
  - SUBLIME_TEXT_VERSION=""

install:
  # Install Sublime Text
  - ./test/install.sh

  # Install `sublime_info`
  - python setup.py develop

  # Install dev requirements
  - pip install -r requirements-dev.txt

before_script:
  # Set up variables for test
  - 'test -n "$SUBLIME_TEXT_VERSION" && export EXPECTED_PATH="/usr/bin/subl"; exit 0'
  - 'test -n "$SUBLIME_TEXT_RENAME" && export EXPECTED_PATH="/usr/bin/$SUBLIME_TEXT_RENAME"; exit 0'
  - 'test -z "$SUBLIME_TEXT_VERSION" && export EXPECT_ERROR="1"; exit 0'
script:
  # Run our tests
  - ./test.sh

notifications:
  email: false
