language: python
python:
  - "2.7"
  # - "3.3"
env:
  - SUBLIME_TEXT_VERSION="2"
  - SUBLIME_TEXT_VERSION="3"

install:
  # Install Sublime Text
  - http://rawgithub.com/twolfson/sublime-installer/SEMVER/install.sh $SUBLIME_TEXT_VERSION | sh
  - subl --version

  # Install `sublime_info`
  - python setup.py develop

script:
  # Run our tests
  - ./test.sh

notifications:
  email: false
