language: python
python:
  - "2.7"
  # - "3.3"
env:
  - SUBLIME_TEXT_VERSION="2"
  - SUBLIME_TEXT_VERSION="3"

install:
  # Install Sublime Text
  - curl http://rawgithub.com/twolfson/sublime-installer/0.1.1/install.sh | sh -s $SUBLIME_TEXT_VERSION
  - subl --version

  # Install `sublime_info`
  - python setup.py develop

script:
  # Run our tests
  - ./test.sh

notifications:
  email: false
